apiVersion: apps/v1
kind: Deployment
metadata:
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    matchLabels:
      app: techtrends
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
        name: techtrends-latest
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
         httpGet:
          path: {{ .Values.livenessProbe.httpGet.path }}
          port: {{ .Values.ports.containerPort }}
        readinessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.httpGet.path }}
            port: {{ .Values.ports.containerPort }}
        ports:
        - containerPort: {{ .Values.ports.containerPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}