apiVersion: apps/v1
kind: Deployment
metadata:
  name:  techtrends
  namespace: sandbox
spec:
  selector:
    matchLabels:
      app: techtrends
  replicas: 1
  template:
    metadata:
      labels:
        app:  techtrends
    spec:
      containers:
      - name:  techtrends
        image: seaquenched/techtrends:latest
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
        livenessProbe:
         httpGet:
          port: 3111
          path: /healthz
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
        ports:
        - containerPort:  3111