apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: sandbox
spec:
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - protocol: TCP
    port: 4111
    targetPort: 3111