
namespace: sandbox

service:
 port: 4111
 targetPort: 3111
 protocol: TCP
 type: ClusterIP

image:
 repository: seaquenched/techtrends
 pullPolicy: IfNotPresent
 tag: latest

replicaCount: 1

resources:
 requests:
  memory: 64Mi
  cpu: 250m
 limits:
  memory: 126Mi
  cpu: 500m

livenessProbe:
  httpGet:
  port: 3111
  path: /healthz
readinessProbe:
  httpGet:
    path: /healthz
    port: 3111
ports:
- containerPort:  3111
